version: '3'
services:
  sse:
    image: postor/sse-notify-server
    ports:
      - "3001:3000"
  next:    
    build: .
    ports:
      - "3000:3000"
    environment:
      SSE_SERVER: "http://127.0.0.1:3001"